# Generated by Django 4.2.20 on 2025-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=True, help_text='Indica si el servicio está disponible actualmente', verbose_name='Disponible'),
        ),
    ]
