# Generated by Django 4.2.20 on 2025-05-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_service_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('AUT', 'Autorizada por mutua'), ('PEN', 'Pendiente de autorizacion'), ('DEN', 'Autorizacion denegada'), ('CON', 'Confirmada')], default='PEN', max_length=3, verbose_name='Estado'),
        ),
    ]
