# Generated by Django 4.2.20 on 2025-04-08 08:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_alter_appointment_options_remove_appointment_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_hour',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_hour',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
