# Generated by Django 4.2.20 on 2025-05-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_appointment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('AUT', 'Autorizada por mutua'), ('DEN', 'Autorizacion denegada'), ('CON', 'Confirmada')], default='PEN', max_length=3, verbose_name='Estado'),
        ),
    ]
