# Generated by Django 4.2.20 on 2025-04-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0004_patient_user'),
    ]

    operations = [
    ]
