# Generated by Django 4.2.20 on 2025-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0006_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
