# Generated by Django 4.2.20 on 2025-06-18 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=21.0, help_text='Ej. 21.00 para 21% IVA', max_digits=5)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada'), ('VENCIDA', 'Vencida')], default='BORRADOR', max_length=10)),
                ('metodo_pago_sugerido', models.CharField(blank=True, max_length=100, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas_pdf/')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cita_origen', models.OneToOneField(blank=True, help_text='Cita que originó esta factura, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_generada_sprint2', to='healthApp.appointment')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_sprint2', to='healthApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_manual', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_factura', to='sprint2.factura')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthApp.service')),
            ],
        ),
    ]
