# Generated by Django 4.2.20 on 2025-05-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0004_alter_appointment_state'),
        ('sprint2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cita_origen',
            field=models.OneToOneField(blank=True, help_text='Cita que originó esta factura, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_generada_sprint2', to='healthApp.appointment'),
        ),
    ]
