name: PR Check Sheet

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Tasks
        id: check-tasks
        run: |
          echo "### ✅ PR Checklist" > checklist.md
          echo "- [ ] Code follows style guidelines" >> checklist.md
          echo "- [ ] Tests have been added/updated" >> checklist.md
          echo "- [ ] Documentation is updated if necessary" >> checklist.md
          echo "- [ ] No console warnings/errors" >> checklist.md
          echo "- [ ] PR description is clear and complete" >> checklist.md

          echo "::set-output name=CHECKLIST::$(cat checklist.md)"

      - name: Comment Check Sheet on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.check-tasks.outputs.CHECKLIST }}

      - name: Fail if Check Sheet Not Completed
        run: exit 1
        if: always()
