name: Pareto Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pareto_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib
      
      - name: Run Pareto analysis script
        run: |
          python pareto.py
      
      - name: Upload Pareto chart
        uses: actions/upload-artifact@v3
        with:
          name: pareto-chart
          path: pareto_chart.png

      - name: Commit and push chart
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add pareto_chart.png
          git commit -m 'Add generated Pareto chart'
          git push
