name: Pareto Analysis

permissions:
  contents: write
  issues: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pareto_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib requests

      - name: Get issues with conventional commits
        id: get_issues
        run: |
          # Use GitHub API to list issues and filter conventional commits (e.g., feat, fix, docs, etc.)
          issues=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open")
          
          # Filter for conventional commit types (for example, 'feat' or 'fix')
          conventional_issues=$(echo "$issues" | jq -r '.[] | select(.title | test("^(feat|fix|docs|chore):")) | .number')

          # Pass the filtered issues to the Python script
          echo "::set-output name=issues::$conventional_issues"

      - name: Run Pareto analysis script
        run: |
          # Pass the issues to the Python script
          python .github/scripts/pareto.py ${{ steps.get_issues.outputs.issues }}

      - name: List files in the repository (for debugging)
        run: |
          ls -la

      - name: Upload Pareto chart
        uses: actions/upload-artifact@v4
        with:
          name: pareto-chart
          path: pareto_chart.png

      - name: Commit and push chart
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -f pareto_chart.png
          git commit -m 'Add generated Pareto chart'
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
