
name: Generate Pareto Diagram

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday
  push:
    branches:
      - main
  issues:
    types:
      - opened
      - closed

jobs:
  generate-pareto:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests matplotlib

    - name: Generate Pareto Diagram
      run: |
        python .github/scripts/generate_pareto.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add pareto_diagram.png
        git commit -m 'Update Pareto Diagram'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
